@startuml "Collect Resources"

state "Collect Resources" as CollectResources : Idle State
state "Collect Wood" as CollectWood : Collect Wood State
state "Collect Ore" as CollectOre : Collect Ore State
state "Protect Self" as ProtectSelf
state "Eat" as Eat

[*] --> CollectResources
CollectResources --> [*] : If done

state "Finish Collecting" as FinishCollecting : Idle State
CollectResources --> CollectOre : If need\nore
CollectOre --> FinishCollecting : If finished
CollectOre --> ProtectSelf : If in\ndanger

CollectResources --> CollectWood : If need\nwood
CollectWood --> CollectResources
CollectWood --> FinishCollecting
CollectWood --> ProtectSelf : If in\ndanger

ProtectSelf --> FinishCollecting
FinishCollecting --> CollectResources : If not\nhungry
FinishCollecting --> Eat : If hungry
Eat --> CollectResources

@enduml